<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-options.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases for all options, as shown in admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php

	Finnish translation: kyyberi (jarkko.moilanen@ossoil.com)


*/

	return array(
		'allow_anon_name' => 'Vaadi nimi anonyymeille kirjoituksille:',
		'allow_change_usernames' => 'Salli käyttäjien muuttaa käyttäjätunnustaan:',
		'allow_close_questions' => 'Salli kysymysten manuaalinen sulkeminen:',
		'allow_login_email_only' => 'Tallenna lokiin vain email osoite (ei käyttäjätunnusta):', 
		'allow_multi_answers' => 'Salli samalta käyttäjältä useita vastauksia (samaan kysymykseen):',
		'allow_no_category' => 'Salli kysymykset ilman kategoriaa',
		'allow_no_sub_category' => 'Salli kysymykset ilman alakategorian valintaa',
		'allow_private_messages' => 'Salli yksityisviestit käyttäjien välillä:',
		'allow_user_walls' => 'Salli seinäkirjoitukset käyttäjien profiiliin:',
		'allow_self_answer' => 'Salli oma vastaus omaan kysymykseen:',
		'allow_view_q_bots' => 'Salli hakukoneiden katsella kysymyksiä',
		'avatar_allow_gravatar' => 'Salli ^1Gravatar^2 käyttö:',
		'avatar_allow_upload' => 'Salli avatarin lataaminen palvelimelle:',
		'avatar_default_show' => 'Oletus avatar:',
		'avatar_message_list_size' => 'Avatarin koko listauksessa:',
		'avatar_profile_size' => 'Avatarin koko profiilisivulla:',
		'avatar_q_list_size' => 'Avatarin koko kysymysten listauksissa:',
		'avatar_q_page_a_size' => 'Avatarin koko vastauksissa:',
		'avatar_q_page_c_size' => 'Avatarin koko kommenteissa:',
		'avatar_q_page_q_size' => 'Avatarin koko kysymyksissä:',
		'avatar_store_size' => 'Avatar kuvien suurin sallittu koko:',
		'avatar_users_size' => 'Avatarin koko pistehirmut listauksessa:',
		'block_bad_words' => 'Sensuroidut sanat - erottele välilyönneillä tai pilkuilla:',
		'block_ips_write' => 'Estetyt IP osoitteet - erottele välilyönneillä tai pilkuilla:',
		'captcha_module' => 'Käytä captchaa:',
		'captcha_on_anon_post' => 'Käytä captchaa anonyymeille kirjoituksille:',
		'captcha_on_feedback' => 'Käytä captchaa palautelomakkeessa:',
		'captcha_on_register' => 'Käytä captchaa rekisteröitymisessä:',
		'captcha_on_reset_password' => 'Käytä captchaa salasanan resetoinnissa:',
		'captcha_on_unconfirmed' => 'Käytä captchaa, jos sähköpostia ei ole vahvistettu:',
		'columns_tags' => 'Tunnistesivun kolumnit:',
		'columns_users' => 'Käyttäjäsivun kolumnit:',
		'comment_on_as' => 'Salli vastausten kommentointi:',
		'comment_on_qs' => 'Salli kysymysten kommentointi:',
		'confirm_user_emails' => 'Pyydä käyttäjiltä sähköpostin vahvistus:',
		'confirm_user_required' => 'Uusien käyttäjien pitää suorittaa vahvistus (email):',
		'custom_home_content' => 'Etusivun sisältö - HTML sallittu:',
		'custom_home_heading' => 'Etusivun otsikko:',
		'default_privacy' => 'Yksityisyys: sähköpostiosoitettasi EI jaeta tai myydä kolmansille osapuolille.',
		'default_sidebar' => 'Tervetuloa Avoindata.net palveluun^, jossa voit kysyä ja saada vastauksia avoimeen dataan liittyvissä asioissa.',
		'default_subject' => 'Viesti käyttäjältä ^',
		'default_suffix' => 'Avoindata.net',
		'do_ask_check_qs' => 'Tarkista samantyyppiset kysymykset kysyttäessä:',
		'do_close_on_select' => 'Sulje kysymykset valitsemalla vastaus:',
		'do_complete_tags' => 'Näytä vastaavat tunnisteet kirjoitettaessa:',
		'do_count_q_views' => 'Laske kysymysten katselumäärät:',
		'do_example_tags' => 'Näytä esimerkkitunnisteet kysymykseen liittyen:',
		'editor_for_as' => 'Oletusarvoinen vastausten muokkain:',
		'editor_for_cs' => 'Oletusarvoinen kommenttien muokkain:',
		'editor_for_qs' => 'Oletusarvoinen kysymysten muokkain:',
		'email_privacy' => 'Yksityisyysviesti koskien sähköpostiosoitteiden yksityisyyttä - HTML sallittu:',
		'extra_field_active' => 'Lisäkenttä kysymyslomakkeessa:',
		'extra_field_display_label' => 'Näytä lisätieto kysymyssivuilla otsikolla:',
		'extra_field_display' => 'Näytä lisätieto kysymyssivuilla',
		'feed_for_activity' => 'Viimeaikaisen aktiivisuuden syöte:',
		'feed_for_hot' => 'Polttavien kysymysten syöte:',
		'feed_for_qa' => 'Viimeaikaisten kysymysten ja vastausten syöte:',
		'feed_for_questions' => 'Viimeaikaisten kysymysten syöte:',
		'feed_for_search' => 'Etsinän tulosten syöte:',
		'feed_for_tag_qs' => 'Jokaisen tunnisteen kysymysten syöte:',
		'feed_for_unanswered' => 'Vastaamattomien kysymysten syöte:',
		'feed_full_text' => 'Sisällytä koko sisältö syötteisiin:',
		'feed_number_items' => 'Syötteiden suurin pituus:',
		'feed_per_category' => 'Yksittäisiä syötteitä kategoriaa kohden:',
		'feedback_email' => 'Sähköpostiosoite ylläpidon viestejä varten - ei näytetä muille käyttäjille:',
		'feedback_enabled' => 'Ota palautesivu käyttöön',
		'flagging_hide_after' => 'Piilota kirjoitukset automaattiesti, kun ne saavuttavat:',
		'flagging_notify_every' => 'Lähetä minulle sähköpostia kun tulee lisäyksiä:',
		'flagging_notify_first' => 'Lähetä minulle sähköpostia jos kirjoitukseen tulee:',
		'flagging_of_posts' => 'Salli kirjoitusten liputtaminen:',
		'follow_on_as' => 'Salli vastauksiin liittyvät kysymykset:',
		'from_email' => 'Lähettäjän shköpostiosoite sivustolta lähtevissä viesteissä:',
		'hot_weight_a_age' => 'Kysymykseen on tullut uusi vastaus:',
		'hot_weight_answers' => 'Kysymykseen on tullut monta vastausta:',
		'hot_weight_q_age' => 'Uusi kysymys:',
		'hot_weight_views' => 'Kysymystä on katseltu useita kertoja:',
		'hot_weight_votes' => 'Kysymykselle on annettu monta ylöspäin peukutusta:',
		'links_in_new_window' => 'Avaa linkitetyt URL -osoitteet uuteen ikkunaan:',
		'logo_height' => 'Logon korkeus:',
		'logo_show' => 'Näytä logokuva sivun yläviitteessä',
		'logo_url' => 'Kuvan URL-osoite - absoluuttinen tai relatiivinen suhteessa Q2A juureen:',
		'logo_width' => 'Logon leveys:',
		'mailing_body' => 'Sisältö:',
		'mailing_enabled' => 'Salli massapostitus',
		'mailing_from_email' => 'Lähettäjän sähköpostiosoite:',
		'mailing_from_name' => 'Lähettäjän nimi:',
		'mailing_per_minute' => 'Suurin sallittu postituksen määrä:',
		'mailing_subject' => 'Aihe:',
		'match_1' => 'Kapein',
		'match_2' => 'Kapemapi',
		'match_3' => 'Oletus',
		'match_4' => 'Leveämpi',
		'match_5' => 'Levein',
		'match_ask_check_qs' => 'Vastaavat kysymykset:',
		'match_example_tags' => 'Vastaavat tunnisteet:',
		'match_related_qs' => 'Liittyvät kysymykset:',
		'max_len_q_title' => 'Kysymyksen otsikon suurin sallittu pituus:',
		'max_num_q_tags' => 'Tunnisteiden suurin sallittu määrä:',
		'max_rate_ip_as' => 'Vastauten lisäämisen määrärajoite:',
		'max_rate_ip_cs' => 'Kommenttien lisäämisen määrärajoite:',
		'max_rate_ip_flags' => 'Kirjoitusten liputtamisen määrärajoite:',
		'max_rate_ip_logins' => 'Sisäänkirjautumisen määrärajoite:',
		'max_rate_ip_messages' => 'Yksityisviestien ja seinäkirjoitusten määrärajoite:',
		'max_rate_ip_qs' => 'Kysymysten kysymisen määrärajoite:',
		'max_rate_ip_registers' => 'Rekisteröitymisen määrärajoite:',
		'max_rate_ip_uploads' => 'Tiedostojen palvelimelle lataamisen määrärajoite:',
		'max_rate_ip_votes' => 'Peukuttamisen määrärajoite:',
		'max_rate_user_as' => 'Vastausten maksimäärä tunnin sisällä (per käyttäjä):',
		'max_rate_user_cs' => 'Kommenttien maksimimäärä tunnin sisällä (per käyttäjä):',
		'max_rate_user_flags' => 'Liputusten maksimimäärä tunnin sisällä (per käyttäjä):',
		'max_rate_user_messages' => 'Yksityisviestien maksimäärä tunnin sisällä (per käyttäjä):',
		'max_rate_user_qs' => 'Kysymysten maksimimäärä tunnin sisällä (per käyttäjä):',
		'max_rate_user_uploads' => 'Palvelimelle lataamisen maksimimäärä tunnin sisällä (per käyttäjä):',
		'max_rate_user_votes' => 'Peukutusten maksimimäärä tunnin sisällä (per käyttäjä):',
		'min_len_a_content' => 'Vastauksen minimipituus:',
		'min_len_c_content' => 'Kommentin minimipituus:',
		'min_len_q_content' => 'Kysymyksen sisällön minimipituus:',
		'min_len_q_title' => 'Kysymyksen otsikon minimipituus:',
		'min_num_q_tags' => 'Tunnisteiden minimimäärä:',
		'moderate_anon_post' => 'Käytä moderointia anonyymeille kirjoituksille:',
		'moderate_by_points' => 'Käytä moderointia käyttäjille, joilla vähäinen määrä pisteitä:',
		'moderate_notify_admin' => 'Lähetä sähköpostia kun moderointia vaaditaan:',
		'moderate_points_limit' => 'Käytä moderointia käyttäjille, joilla pisteitä vähemmän kuin:',
		'moderate_unconfirmed' => 'Käytä moderointia, jos sähköposti ei ole vahvistettu:',
		'neat_urls' => 'URL rakenne:',
		'notify_admin_q_post' => 'Lähetä tähän osoitteeseen sähköpostia kun kysymys on esitetty',
		'notify_users_default' => 'Aseta sähköposti-ilmoitus oletusarvo:',
		'option_default' => 'Oletus',
		'page_size_activity' => 'Kaiken aktiivisuuden pituus:',
		'page_size_ask_check_qs' => 'Samantyyppisten kysymysten esittämisen maksimimäärä:',
		'page_size_ask_tags' => 'Tarjottavien tunnisteiden maksimimäärä:',
		'page_size_home' => 'Q&A sivun pituus:',
		'page_size_hot_qs' => 'Polttavaa! sivun pituus:',
		'page_size_q_as' => 'Vastausten maksimimäärä per sivu:',
		'page_size_qs' => 'Kysymysten sivun pituus:',
		'page_size_related_qs' => 'Liittyvien kysymysten maksimimäärä:',
		'page_size_search' => 'Tuloksien (etsintä) määrä per sivu:',
		'page_size_tag_qs' => 'Kysymystä / tunnistesivu:',
		'page_size_tags' => 'Tunnistesivujen pituus:',
		'page_size_una_qs' => 'Vastaamattomien sivun pituus:',
		'page_size_users' => 'Käyttäjät sivun pituus:',
		'pages_prev_next' => 'Linkit edellinen/seuraava sivuille:',
		'permit_admins' => 'Ylläpitäjät',
		'permit_all' => 'Kuka tahansa',
		'permit_block' => 'Käyttäjien tai IP-osoitteiden esto tai eston poisto:',
		'permit_confirmed' => 'Rekisteröityneet käyttäjät - sähköpostiosoite vahvistettu',
		'permit_create_admins' => 'Ylläpitäjien luominen:',
		'permit_create_eds_mods' => 'Muokkaajien ja moderaattorien luominen:',
		'permit_create_experts' => 'Experttien luominen:',
		'permit_delete_users' => 'Käyttäjien poisto:',
		'permit_editors' => 'Muokkaajat, moderaattorit, ylläpitäjät',
		'permit_experts' => 'Experttit, muokkaajat, moderoijat, ylläpitäjät',
		'permit_moderators' => 'Moderaattorit ja ylläpitäjät',
		'permit_points_confirmed' => 'Rekisteröityneet käyttäjät & vahvistettu spostiosoite & tarpeeksi pisteitä',
		'permit_points' => 'Rekisteröityneet käyttäjät, joilla tarpeeksi pisteitä',
		'permit_see_emails' => 'Kaikkien sähköpostiosoitteiden katselu:',
		'permit_supers' => 'Super ylläpitäjät',
		'permit_users' => 'Rekisteröityneet käyttäjät',
		'place_full_below_content' => 'Täysi leveys - sisällön alla',
		'place_full_below_footer' => 'Täysi leveys - alaviitteen alla',
		'place_full_below_nav' => 'Täysi leveys - navigoinnin alla',
		'place_full_top' => 'Täysi leveys - sivun yläreunassa',
		'place_main_below_lists' => 'Sisältöalueella - listojen alla',
		'place_main_below_title' => 'Sisältöalueella - otsikon alla',
		'place_main_bottom' => 'Sisältöalueella - alimmaisena',
		'place_main_top' => 'Main area - Top',
		'place_side_below_categories' => 'Side panel - Below categories',
		'place_side_below_sidebar' => 'Side panel - Below sidebar box',
		'place_side_last' => 'Side panel - Last',
		'place_side_top' => 'Side panel - Top',
		'points_a_selected' => 'Having your answer selected as the best:',
		'points_a_voted_max_gain' => 'Limit from up votes on each answer:',
		'points_a_voted_max_loss' => 'Limit from down votes on each answer:',
		'points_base' => 'Lisää kaikille käyttäjille:',
		'points_multiple' => 'Pisteiden kerroin:',
		'points_per_a_voted_down' => 'Per vastauksesi alaspäin peukutus:',
		'points_per_a_voted_up' => 'Per vastauksesi ylöspäin peukutus:',
		'points_per_q_voted_down' => 'Per kysymyksesi alaspäin peukutus:',
		'points_per_q_voted_up' => 'Per kysymyksesi ylöspäin peukutus:',
		'points_post_a' => 'Vastauksen lähetys:',
		'points_post_q' => 'Kysymyksen lähetys:',
		'points_q_voted_max_gain' => 'Kysymyskohtainen raja ylöspäin peukuttamiselle:',
		'points_q_voted_max_loss' => 'Kysymyskohtainen raja alaspäin peukuttamiselle:',
		'points_select_a' => 'Vastauksen valinta kysymykseesi:',
		'points_vote_down_a' => 'Vastauksen alaspäin peukuttaminen:',
		'points_vote_down_q' => 'Kysymyksen alaspäin peukuttaminen:',
		'points_vote_up_a' => 'Vastausten ylöspäin peukuttaminen:',
		'points_vote_up_q' => 'Kysymysten ylöspäin peukuttaminen:',
		'q_urls_remove_accents' => 'Poista aksenttimerkit kysymysten URL:sta:',
		'q_urls_title_length' => 'Kysymyksen otsikon pituus URL:ssa:',
		'search_module' => 'Käytä etsintään modulia:',
		'show_a_form_immediate' => 'Näytä vastauslomake heti:',
		'show_always' => 'Aina',
		'show_c_reply_buttons' => 'Näytä vastaa nappi kommenteissa:',
		'show_custom_answer' => 'Mukautettu viesti vastauslomakkeessa - HTML sallittu:',
		'show_custom_ask' => 'Mukautettu viesti kysymyslomakkeessa - HTML sallittu:',
		'show_custom_comment' => 'Mukautettu viesti kommenttilomakkeessa - HTML sallittu:',
		'show_custom_footer' => 'Mukautettu HTML sisältö joka sivun alareunassa:',
		'show_custom_header' => 'Mukautettu HTML sisältö joka sivun yläreunassa:',
		'show_custom_home' => 'Mukautettu sisältö etusivulla Q&A sijasta',
		'show_custom_in_head' => 'Mukautettu HTML <HEAD> osuus joka sivulla:',
		'show_custom_register' => 'Mukautettu viesti rekisteröintilomakkeessa - HTML sallittu:',
		'show_custom_sidebar' => 'Mukautettu HTML sisältö sivupaneelin laatikossa joka sivulla:',
		'show_custom_sidepanel' => 'Mukautettu HTML sisältö joka sivulla sivupaneelissa:',
		'show_custom_welcome' => 'Custom message in email sent to new registered users:',
		'show_fewer_cs_count' => 'Jos osittain piilotettu, näytä tuorein:',
		'show_fewer_cs_from' => 'Piilota kommentit osittain jos kirjoituksesta on kulunut:',
		'show_full_date_days' => 'Näytä koko päiväys kun kirjoituksesta on kulunut:',
		'show_home_description' => 'Sisällytä <META> kuvaus etusivulle:',
		'show_if_no_as' => 'Näytä, jos ei vastauksia',
		'show_message_history' => 'Tallenna ja näytä yksityisviestien historia:',
		'show_never' => 'Ei koskaan',
		'show_notice_visitor' => 'Ilmoitus uusille sivun yläreunassa vierailijoille (1. kerralla) - HTML merkkaus sallittu:',
		'show_notice_welcome' => 'Ilmoitus uusille sivun yläreunassa uusille käyttäjille - HTML merkkaus sallittu:',
		'show_selected_first' => 'Siirrä valittu vastaus sivun yläreunaan:',
		'show_url_links' => 'Tunnista ja linkitä kirjoitusten URL:t:',
		'show_user_points' => 'Näytä pistemäärä käyttäjänimen vieressä:',
		'show_user_titles' => 'Näytä tittelit käyttäjien nimen vieressä:',
		'show_view_counts' => 'Näytä katselumäärä kysymysten listauksissa:',
		'show_when_created' => 'Näytä kirjoitusten ikä:',
		'site_language' => 'Käyttöliittymän kieli:',
		'site_maintenance' => 'Ota sivusto pois käytöstä ylläpitoa varten',
		'site_theme_mobile' => 'Mobiili teema:',
		'site_theme' => 'Sivuston teema:',
		'site_title' => 'Q&A sivuston nimi:',
		'site_url' => 'Ensijainen sivuston URL:',
		'smtp_active' => 'Lähetä sähköpostia SMTP:llä paikallisen deamonin sijasta',
		'smtp_address' => 'SMTP palvelimen osoite:',
		'smtp_authenticate' => 'Lähetä SMTP käyttäjätunnus ja salasanana',
		'smtp_password' => 'SMTP salasana:',
		'smtp_port' => 'SMTP palvalimen portti:',
		'smtp_secure_none' => 'Ei mitään',
		'smtp_secure' => 'Turvallinen SMTP yhteys:',
		'smtp_username' => 'SMTP käyttäjänimi:',
		'sort_answers_by' => 'Järjestä vastaukset:',
		'sort_time' => 'Aika',
		'sort_votes' => 'Peukutukset',
		'suspend_register_users' => 'Estä tilapäisesti uudet rekisteröitymiset:',
		'tag_separator_comma' => 'Käytä ainoastaan pilkkua (,) tagien erottimena:',
		'tags_or_categories' => 'Kysymysten luokitus:',
		'votes_separated' => 'Näytä ylös ja alas peukutus erikseen:',
		'voting_on_as' => 'Salli vastausten peukutus:',
		'voting_on_q_page_only' => 'Salli peukutus vain kysymyssivulla:',
		'voting_on_qs' => 'Salli kysymysten peukutus:',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
