<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-options.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases for all options, as shown in admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php

	Finnish translation: kyyberi (jarkko.moilanen@ossoil.com)


*/

	return array(
		'allow_anon_name' => 'Vaadi nimi anonyymeille kirjoituksille:',
		'allow_change_usernames' => 'Salli käyttäjien muuttaa käyttäjätunnustaan:',
		'allow_close_questions' => 'Salli kysymysten manuaalinen sulkeminen:',
		'allow_login_email_only' => 'Tallenna lokiin vain email osoite (ei käyttäjätunnusta):', 
		'allow_multi_answers' => 'Salli samalta käyttäjältä useita vastauksia (samaan kysymykseen):',
		'allow_no_category' => 'Salli kysymykset ilman kategoriaa',
		'allow_no_sub_category' => 'Salli kysymykset ilman alakategorian valintaa',
		'allow_private_messages' => 'Salli yksityisviestit käyttäjien välillä:',
		'allow_user_walls' => 'Salli seinäkirjoitukset käyttäjien profiiliin:',
		'allow_self_answer' => 'Salli oma vastaus omaan kysymykseen:',
		'allow_view_q_bots' => 'Salli hakukoneiden katsella kysymyksiä',
		'avatar_allow_gravatar' => 'Salli ^1Gravatar^2 käyttö:',
		'avatar_allow_upload' => 'Salli avatarin lataaminen palvelimelle:',
		'avatar_default_show' => 'Oletus avatar:',
		'avatar_message_list_size' => 'Avatarin koko listauksessa:',
		'avatar_profile_size' => 'Avatarin koko profiilisivulla:',
		'avatar_q_list_size' => 'Avatarin koko kysymysten listauksissa:',
		'avatar_q_page_a_size' => 'Avatarin koko vastauksissa:',
		'avatar_q_page_c_size' => 'Avatarin koko kommenteissa:',
		'avatar_q_page_q_size' => 'Avatarin koko kysymyksissä:',
		'avatar_store_size' => 'Avatar kuvien suurin sallittu koko:',
		'avatar_users_size' => 'Avatarin koko pistehirmut listauksessa:',
		'block_bad_words' => 'Sensuroidut sanat - erottele välilyönneillä tai pilkuilla:',
		'block_ips_write' => 'Estetyt IP osoitteet - erottele välilyönneillä tai pilkuilla:',
		'captcha_module' => 'Käytä captchaa:',
		'captcha_on_anon_post' => 'Käytä captchaa anonyymeille kirjoituksille:',
		'captcha_on_feedback' => 'Käytä captchaa palautelomakkeessa:',
		'captcha_on_register' => 'Käytä captchaa rekisteröitymisessä:',
		'captcha_on_reset_password' => 'Käytä captchaa salasanan resetoinnissa:',
		'captcha_on_unconfirmed' => 'Käytä captchaa, jos sähköpostia ei ole vahvistettu:',
		'columns_tags' => 'Tunnistesivun kolumnit:',
		'columns_users' => 'Käyttäjäsivun kolumnit:',
		'comment_on_as' => 'Salli vastausten kommentointi:',
		'comment_on_qs' => 'Salli kysymysten kommentointi:',
		'confirm_user_emails' => 'Pyydä käyttäjiltä sähköpostin vahvistus:',
		'confirm_user_required' => 'Uusien käyttäjien pitää suorittaa vahvistus (email):',
		'custom_home_content' => 'Etusivun sisältö - HTML sallittu:',
		'custom_home_heading' => 'Etusivun otsikko:',
		'default_privacy' => 'Yksityisyys: sähköpostiosoitettasi EI jaeta tai myydä kolmansille osapuolille.',
		'default_sidebar' => 'Tervetuloa Avoindata.net palveluun^, jossa voit kysyä ja saada vastauksia avoimeen dataan liittyvissä asioissa.',
		'default_subject' => 'Viesti käyttäjältä ^',
		'default_suffix' => 'Avoindata.net',
		'do_ask_check_qs' => 'Tarkista samantyyppiset kysymykset kysyttäessä:',
		'do_close_on_select' => 'Sulje kysymykset valitsemalla vastaus:',
		'do_complete_tags' => 'Näytä vastaavat tunnisteet kirjoitettaessa:',
		'do_count_q_views' => 'Laske kysymysten katselumäärät:',
		'do_example_tags' => 'Näytä esimerkkitunnisteet kysymykseen liittyen:',
		'editor_for_as' => 'Oletusarvoinen vastausten muokkain:',
		'editor_for_cs' => 'Oletusarvoinen kommenttien muokkain:',
		'editor_for_qs' => 'Oletusarvoinen kysymysten muokkain:',
		'email_privacy' => 'Yksityisyysviesti koskien sähköpostiosoitteiden yksityisyyttä - HTML sallittu:',
		'extra_field_active' => 'Lisäkenttä kysymyslomakkeessa:',
		'extra_field_display_label' => 'Näytä lisätieto kysymyssivuilla otsikolla:',
		'extra_field_display' => 'Näytä lisätieto kysymyssivuilla',
		'feed_for_activity' => 'Viimeaikaisen aktiivisuuden syöte:',
		'feed_for_hot' => 'Polttavien kysymysten syöte:',
		'feed_for_qa' => 'Viimeaikaisten kysymysten ja vastausten syöte:',
		'feed_for_questions' => 'Viimeaikaisten kysymysten syöte:',
		'feed_for_search' => 'Etsinän tulosten syöte:',
		'feed_for_tag_qs' => 'Feed for each tag\'s questions:',
		'feed_for_unanswered' => 'Feed for unanswered questions:',
		'feed_full_text' => 'Include full text in feeds:',
		'feed_number_items' => 'Maximum length of feeds:',
		'feed_per_category' => 'Individual feeds per category:',
		'feedback_email' => 'Email address for admin messages - not shown to users:',
		'feedback_enabled' => 'Provide a page for users to send feedback',
		'flagging_hide_after' => 'Automatically hide posts which reach:',
		'flagging_notify_every' => 'Email me again after every additional:',
		'flagging_notify_first' => 'Email me if a post receives:',
		'flagging_of_posts' => 'Allow posts to be flagged:',
		'follow_on_as' => 'Allow questions to be related to answers:',
		'from_email' => 'Sender address for messages from site:',
		'hot_weight_a_age' => 'Question has a new answer:',
		'hot_weight_answers' => 'Question has many answers:',
		'hot_weight_q_age' => 'Question is new:',
		'hot_weight_views' => 'Question has many views:',
		'hot_weight_votes' => 'Question has many up votes:',
		'links_in_new_window' => 'Open linked URLs in a new window:',
		'logo_height' => 'Logo height:',
		'logo_show' => 'Show a logo image in the page header',
		'logo_url' => 'URL of logo - absolute or relative to Q2A root:',
		'logo_width' => 'Logo width:',
		'mailing_body' => 'Body text:',
		'mailing_enabled' => 'Enable mass mailings to all users',
		'mailing_from_email' => 'From email address:',
		'mailing_from_name' => 'From name:',
		'mailing_per_minute' => 'Maximum mailing rate:',
		'mailing_subject' => 'Subject line:',
		'match_1' => 'Narrowest',
		'match_2' => 'Narrower',
		'match_3' => 'Default',
		'match_4' => 'Wider',
		'match_5' => 'Widest',
		'match_ask_check_qs' => 'Similar questions matching:',
		'match_example_tags' => 'Example tags matching:',
		'match_related_qs' => 'Related questions matching:',
		'max_len_q_title' => 'Maximum length of question title:',
		'max_num_q_tags' => 'Maximum number of tags:',
		'max_rate_ip_as' => 'Rate limit for adding answers:',
		'max_rate_ip_cs' => 'Rate limit for posting comments:',
		'max_rate_ip_flags' => 'Rate limit for flagging posts:',
		'max_rate_ip_logins' => 'Rate limit for logging in:',
		'max_rate_ip_messages' => 'Rate limit for private and wall messages:',
		'max_rate_ip_qs' => 'Rate limit for asking questions:',
		'max_rate_ip_registers' => 'Rate limit for user registrations:',
		'max_rate_ip_uploads' => 'Rate limit for uploading files:',
		'max_rate_ip_votes' => 'Rate limit for voting:',
		'max_rate_user_as' => 'Maximum answers per user per hour:',
		'max_rate_user_cs' => 'Maximum comments per user per hour:',
		'max_rate_user_flags' => 'Maximum flags per user per hour:',
		'max_rate_user_messages' => 'Maximum private messages per user per hour:',
		'max_rate_user_qs' => 'Maximum questions per user per hour:',
		'max_rate_user_uploads' => 'Maximum uploads per user per hour:',
		'max_rate_user_votes' => 'Maximum votes per user per hour:',
		'min_len_a_content' => 'Minimum length of answer:',
		'min_len_c_content' => 'Minimum length of comment:',
		'min_len_q_content' => 'Minimum length of question body:',
		'min_len_q_title' => 'Minimum length of question title:',
		'min_num_q_tags' => 'Minimum number of tags:',
		'moderate_anon_post' => 'Use moderation for anonymous posts:',
		'moderate_by_points' => 'Use moderation for users with few points:',
		'moderate_notify_admin' => 'Email me when a post needs moderation:',
		'moderate_points_limit' => 'Use moderation for users with less than:',
		'moderate_unconfirmed' => 'Use moderation if email not confirmed:',
		'neat_urls' => 'URL structure:',
		'notify_admin_q_post' => 'Email this address when a question is posted',
		'notify_users_default' => 'Check email notification box by default:',
		'option_default' => 'Default',
		'page_size_activity' => 'Length of All Activity page:',
		'page_size_ask_check_qs' => 'Maximum similar questions to show:',
		'page_size_ask_tags' => 'Maximum tag hints to show:',
		'page_size_home' => 'Length of Q&A page:',
		'page_size_hot_qs' => 'Length of Hot! page:',
		'page_size_q_as' => 'Maximum answers per page:',
		'page_size_qs' => 'Length of Questions page:',
		'page_size_related_qs' => 'Maximum related questions:',
		'page_size_search' => 'Search results per page:',
		'page_size_tag_qs' => 'Questions on each tag page:',
		'page_size_tags' => 'Length of Tags page:',
		'page_size_una_qs' => 'Length of Unanswered page:',
		'page_size_users' => 'Length of Users page:',
		'pages_prev_next' => 'Links to previous/next pages:',
		'permit_admins' => 'Administrators',
		'permit_all' => 'Anybody',
		'permit_block' => 'Blocking or unblocking user or IPs:',
		'permit_confirmed' => 'Registered users with email confirmed',
		'permit_create_admins' => 'Creating administrators:',
		'permit_create_eds_mods' => 'Creating editors and moderators:',
		'permit_create_experts' => 'Creating experts:',
		'permit_delete_users' => 'Deleting users:',
		'permit_editors' => 'Editors, Moderators, Admins',
		'permit_experts' => 'Experts, Editors, Moderators, Admins',
		'permit_moderators' => 'Moderators and Admins',
		'permit_points_confirmed' => 'Registered & email confirmed & enough points',
		'permit_points' => 'Registered users with enough points',
		'permit_see_emails' => 'Viewing user email addresses:',
		'permit_supers' => 'Super Administrators',
		'permit_users' => 'Registered users',
		'place_full_below_content' => 'Full width - Below content',
		'place_full_below_footer' => 'Full width - Below footer',
		'place_full_below_nav' => 'Full width - Below navigation',
		'place_full_top' => 'Full width - Top of page',
		'place_main_below_lists' => 'Main area - Below lists',
		'place_main_below_title' => 'Main area - Below title',
		'place_main_bottom' => 'Main area - Bottom',
		'place_main_top' => 'Main area - Top',
		'place_side_below_categories' => 'Side panel - Below categories',
		'place_side_below_sidebar' => 'Side panel - Below sidebar box',
		'place_side_last' => 'Side panel - Last',
		'place_side_top' => 'Side panel - Top',
		'points_a_selected' => 'Having your answer selected as the best:',
		'points_a_voted_max_gain' => 'Limit from up votes on each answer:',
		'points_a_voted_max_loss' => 'Limit from down votes on each answer:',
		'points_base' => 'Lisää kaikille käyttäjille:',
		'points_multiple' => 'Pisteiden kerroin:',
		'points_per_a_voted_down' => 'Per vastauksesi alaspäin peukutus:',
		'points_per_a_voted_up' => 'Per vastauksesi ylöspäin peukutus:',
		'points_per_q_voted_down' => 'Per kysymyksesi alaspäin peukutus:',
		'points_per_q_voted_up' => 'Per kysymyksesi ylöspäin peukutus:',
		'points_post_a' => 'Vastauksen lähetys:',
		'points_post_q' => 'Kysymyksen lähetys:',
		'points_q_voted_max_gain' => 'Kysymyskohtainen raja ylöspäin peukuttamiselle:',
		'points_q_voted_max_loss' => 'Kysymyskohtainen raja alaspäin peukuttamiselle:',
		'points_select_a' => 'Vastauksen valinta kysymykseesi:',
		'points_vote_down_a' => 'Vastauksen alaspäin peukuttaminen:',
		'points_vote_down_q' => 'Kysymyksen alaspäin peukuttaminen:',
		'points_vote_up_a' => 'Vastausten ylöspäin peukuttaminen:',
		'points_vote_up_q' => 'Kysymysten ylöspäin peukuttaminen:',
		'q_urls_remove_accents' => 'Poista aksenttimerkit kysymysten URL:sta:',
		'q_urls_title_length' => 'Kysymyksen otsikon pituus URL:ssa:',
		'search_module' => 'Käytä etsintään modulia:',
		'show_a_form_immediate' => 'Näytä vastauslomake heti:',
		'show_always' => 'Aina',
		'show_c_reply_buttons' => 'Näytä vastaa nappi kommenteissa:',
		'show_custom_answer' => 'Mukautettu viesti vastauslomakkeessa - HTML sallittu:',
		'show_custom_ask' => 'Mukautettu viesti kysymyslomakkeessa - HTML sallittu:',
		'show_custom_comment' => 'Mukautettu viesti kommenttilomakkeessa - HTML sallittu:',
		'show_custom_footer' => 'Mukautettu HTML sisältö joka sivun alareunassa:',
		'show_custom_header' => 'Mukautettu HTML sisältö joka sivun yläreunassa:',
		'show_custom_home' => 'Mukautettu sisältö etusivulla Q&A sijasta',
		'show_custom_in_head' => 'Mukautettu HTML <HEAD> osuus joka sivulla:',
		'show_custom_register' => 'Mukautettu viesti rekisteröintilomakkeessa - HTML sallittu:',
		'show_custom_sidebar' => 'Mukautettu HTML sisältö sivupaneelin laatikossa joka sivulla:',
		'show_custom_sidepanel' => 'Mukautettu HTML sisältö joka sivulla sivupaneelissa:',
		'show_custom_welcome' => 'Custom message in email sent to new registered users:',
		'show_fewer_cs_count' => 'Jos osittain piilotettu, näytä tuorein:',
		'show_fewer_cs_from' => 'Piilota kommentit osittain jos kirjoituksesta on kulunut:',
		'show_full_date_days' => 'Näytä koko päiväys kun kirjoituksesta on kulunut:',
		'show_home_description' => 'Sisällytä <META> kuvaus etusivulle:',
		'show_if_no_as' => 'Näytä, jos ei vastauksia',
		'show_message_history' => 'Tallenna ja näytä yksityisviestien historia:',
		'show_never' => 'Ei koskaan',
		'show_notice_visitor' => 'Ilmoitus uusille sivun yläreunassa vierailijoille (1. kerralla) - HTML merkkaus sallittu:',
		'show_notice_welcome' => 'Ilmoitus uusille sivun yläreunassa uusille käyttäjille - HTML merkkaus sallittu:',
		'show_selected_first' => 'Siirrä valittu vastaus sivun yläreunaan:',
		'show_url_links' => 'Tunnista ja linkitä kirjoitusten URL:t:',
		'show_user_points' => 'Näytä pistemäärä käyttäjänimen vieressä:',
		'show_user_titles' => 'Näytä tittelit käyttäjien nimen vieressä:',
		'show_view_counts' => 'Näytä katselumäärä kysymysten listauksissa:',
		'show_when_created' => 'Näytä kirjoitusten ikä:',
		'site_language' => 'Käyttöliittymän kieli:',
		'site_maintenance' => 'Ota sivusto pois käytöstä ylläpitoa varten',
		'site_theme_mobile' => 'Mobiili teema:',
		'site_theme' => 'Sivuston teema:',
		'site_title' => 'Q&A sivuston nimi:',
		'site_url' => 'Ensijainen sivuston URL:',
		'smtp_active' => 'Lähetä sähköpostia SMTP:llä paikallisen deamonin sijasta',
		'smtp_address' => 'SMTP palvelimen osoite:',
		'smtp_authenticate' => 'Lähetä SMTP käyttäjätunnus ja salasanana',
		'smtp_password' => 'SMTP salasana:',
		'smtp_port' => 'SMTP palvalimen portti:',
		'smtp_secure_none' => 'Ei mitään',
		'smtp_secure' => 'Turvallinen SMTP yhteys:',
		'smtp_username' => 'SMTP käyttäjänimi:',
		'sort_answers_by' => 'Järjestä vastaukset:',
		'sort_time' => 'Aika',
		'sort_votes' => 'Peukutukset',
		'suspend_register_users' => 'Estä tilapäisesti uudet rekisteröitymiset:',
		'tag_separator_comma' => 'Käytä ainoastaan pilkkua (,) tagien erottimena:',
		'tags_or_categories' => 'Kysymysten luokitus:',
		'votes_separated' => 'Näytä ylös ja alas peukutus erikseen:',
		'voting_on_as' => 'Salli vastausten peukutus:',
		'voting_on_q_page_only' => 'Salli peukutus vain kysymyssivulla:',
		'voting_on_qs' => 'Salli kysymysten peukutus:',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
