<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-admin.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases for admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php

        Finnish translation: kyyberi (jarkko.moilanen@ossoil.com)

*/

	return array(
		'active_widgets_explanation' => 'Aktiiviset vimpaimet:',
		'add_category_button' => 'Lisää kategoria',
		'add_field_button' => 'Lisää kenttä',
		'add_link_button' => 'Lisää linkki',
		'add_link_link' => ' - ^1lisää linkki^2',
		'add_new_field' => 'Lisää uusi kenttä',
		'add_new_title' => 'Lisää uusi otsikko',
		'add_page_button' => 'Lisää sivu',
		'add_title_button' => 'Lisää otsikko',
		'add_widget_button' => 'Lisää vimpain',
		'add_widget_link' => ' - ^1Lisää vimpain^2',
		'admin_title' => 'Hallinnointikeskus',
		'after_footer' => 'Linkkien jälkeen alaviitteessä',
		'after_main_menu' => 'Välilehtien jälkeen ylhäällä',
		'after_x_tab' => '"^" välilehden jälkeen',
		'after_x' => '"^" jälkeen',
		'moderate_title' => 'Moderoi',
		'basic_editor' => 'Peruseditori',
		'before_main_menu' => 'Ennen yläosan välilehtiä',
		'block_ips_note' => 'Käytä väliviivaa alueen määrittämiseen tai *:ä villinä korttina. Esimerkit: 192.168.0.4 , 192.168.0.0-192.168.0.31 , 192.168.0.*',
		'block_words_note' => 'Käytä *:ä villinä korttina. Esimerkit: puh (sisältää vain tasan sanat, joissa kirjaimet puh) , puh* (sisältää sanat, jotka alkavat puh) , puh*t (sisältää esimerkiksi sanat: puheet, puhtaat).',
		'cancel_mailing_button' => 'Peru sähköpostin lähettäminen',
		'categories_introduction' => 'Päästäksesi alkuun kategorioiden kanssa, valitse \'Lisää kategoria\'.',
		'categories_not_shown' => 'Joissakin kysymyksissä on kategoria ja niitä ei näytetä/listata.',
		'categories_title' => 'Kategoriat',
		'categories' => 'Kategoriat',
		'category_add_sub' => 'lisää alakategoria',
		'category_added' => 'Kategoria lisätty',
		'category_already_used' => 'Tämä kategoria on jo käytössä',
		'category_default_slug' => 'kategoria-^',
		'category_description' => 'Valinnainen kategorian kuvaus:',
		'category_max_depth_x' => 'Jotkin asetukset saattavat olla piilotettuja, jotta voidaan estää kategorian syvyys ^ tasolle.',
		'category_move_parent' => 'siirrä toisen kategorian alle',
		'category_name_first' => 'Ensimmäisen kategorian nimi:',
		'category_name' => 'Kategorian nimi:',
		'category_no_add_subs_x' => 'Tällä kategorialla ei voi olla alakategorioita, koska se on jo tasolla ^.',
		'category_no_delete_subs' => 'Kategoriaa ei voi poistaa, koska sillä on alakategorioita.',
		'category_no_sub_error' => '^q kysymyksillä tässä kategoriassa ei ole alakategorioita - ^1aseta alakategoria^2',
		'category_no_sub_to' => 'Siirrä kysymykset ilman alakategoriaa sijainnissa ^ uuteen paikkaan:',
		'category_no_subs' => 'Ei yhtään',
		'category_none_error' => '^q kysymyksillä ei ole kategoriaa - ^1aseta kategoria^2',
		'category_none_to' => 'Aseta kategoria kysymyksille, jotka ovat ilman kategoriaa:',
		'category_parent' => 'Ylempi kategoria:',
		'category_saved' => 'Kategoria tallennettu',
		'category_slug' => 'Kategoria tunniste - URL:n osa:',
		'category_subs' => 'Alakategoriat:',
		'category_top_level' => 'Ei ylempää tasoa (ylin taso)',
		'characters' => 'merkkiä',
		'check_language_suffix' => ' - ^1tarkista vaihtoehtoiset kielet^2',
		'click_name_edit' => 'Mukautetut sivut tai linkit:',
		'database_cleanup' => 'Tietokannan siivoustoiminnot',
		'delete_category_reassign' => 'Poista kategoria ja liitä kysymykset kategoriaan:',
		'delete_category' => 'Poista tämä kategoria',
		'delete_field' => 'Poista tämä kenttä',
		'delete_hidden_complete' => 'Kaikki piilotetut kysymykset ilman riippuvuuksia/viittauksia on poistettu',
		'delete_hidden_note' => ' - kaikki piilotetut kysymykset, vastaukset ja kommentit ilman riippuvuuksia/viittauksia',
		'delete_hidden' => 'Poista piilotetut kirjoitukset',
		'delete_link' => 'Poista tämä linkki',
		'delete_page' => 'Poista sivu',
		'delete_stop' => 'Lopeta poistaminen',
		'delete_title' => 'Poista otsikko',
		'delete_widget_position' => 'Poista vimpain tästä sijainnista',
		'edit_custom_page' => 'Muokkaa mukautettua sivua',
		'edit_field' => ' - ^1muokkaa kenttää^2',
		'edit_link' => ' - ^1muokkaa linkkiä^2',
		'edit_page' => ' - ^1muokkaa sivua^2',
		'edit_title' => ' - ^1muokkaa otsikkoa^2',
		'emails_per_minute' => 'sähköpostia minuutissa',
		'emails_title' => 'Sähköpostit',
		'feed_link_example' => 'Esimerkki syöte',
		'feed_link' => 'Syöte',
		'feeds_title' => 'RSS syötteet',
		'field_link_url' => 'Linkitetty URL',
		'field_multi_line' => 'Usean rivin sisältö',
		'field_name' => 'Kentän nimi:',
		'field_single_line' => 'Yhden rivin sisältö',
		'field_type' => 'Sisältötyyppi:',
		'first' => 'Ensimmäinen',
		'flagged_title' => 'Liputettu',
		'form_security_expired' => 'Lomakkeen turvakoodi on vanhentunut - yritä uudelleen',
		'from_anon' => 'Tuntemattomalta:',
		'from_users' => 'Käyttäjiltä:',
		'general_title' => 'Yleinen',
		'hidden_answers_deleted' => 'Poistettu ^1 / ^2 piilotettua vastausta...',
		'hidden_comments_deleted' => 'Poistettu ^1 / ^2 piilotettua kommenttia...',
		'hidden_questions_deleted' => 'Poistettu ^1 / ^2 piilotettua kysymystä...',
		'hotness_factors' => 'Kysymyksen polttavuuden suhteellinen tärkeys:',
		'hidden_title' => 'Piilotettu',
		'installed_plugins' => 'Asennetut liitännäiset:',
		'ip_address_pages' => 'IP osoitteiden sivu',
		'layout_title' => 'Asettelu',
		'link_name' => 'Linkin teksti:',
		'link_new_window' => 'Avaa linkki uuteen ikkunaan',
		'link_url' => 'Linkin URL-osoite - absoluuttinen tai relatiivinen suhteessa Q2A juureen:',
		'lists_title' => 'Listat',
		'mailing_complete' => 'Postitus on valmis',
		'mailing_explanation' => 'Käyttäjät voivat peruuttaa tilauksen profiilisivun kautta.',
		'mailing_progress' => 'Postitus ^1 / ^2 valmis...',
		'mailing_title' => 'Postitus',
		'mailing_unsubscribe' => 'Joka viestin alaosaan lisätään tilauksen peruttamisen linkki.',
		'maintenance_admin_only' => 'Sivusto on ^1ylläpidossa^2 eikä ole käytettävissä (paitsi admineille).',
		'maximum_x' => ' (maksimi ^)',
		'module_x_database_init' => '^1 ^2 moduli vaatii ^3tietokannan alustamisen^4.',
		'most_flagged_title' => 'Liputettu sisältö',
		'mysql_version' => 'MySQL versio:',
		'nav_links_explanation' => 'Näytä navigointilinkit:',
		'nav_qa_is_home' => 'Q&A (linkit etusivulle)',
		'neat_urls_note' => ' (vaatii ^1htaccess^2 tiedoston)',
		'no_approve_found' => 'Ei hyväksymistä vaille olevaa sisältöä',
		'no_classification' => 'Ei yhtään',
		'no_flagged_found' => 'Ei liputettua sisältöä',
		'no_hidden_found' => 'Ei piilotettua sisältöä',
		'no_image_gd' => 'PHP versio on käännetty ilman GD kuvatukea. Käyttäjät eivät voi ladata avatar-kuvaansa suoraan.',
		'no_link' => 'Ei linkkiä',
		'no_multibyte' => 'PHP versio on käännetty ilman monitavutukea (multibyte string support). Hakutoiminto on siksi tehottomampi ei-Roomalaisille merkistöille.',
		'no_plugin_options' => 'Millään asennetulla liitännäisellä ei ole näytettäviä valintoja.',
		'no_privileges' => 'Sallittu vain ylläpitäjille.',
		'not_logged_in' => '^1Kirjaudu sisään^2 ylläpitäjänä nähdäksesi sivun.',
		'opposite_main_menu' => 'Ylhäällä olevien välilehtien äärilaidassa',
		'options_reset' => 'Valinnat resetoitu',
		'options_saved' => 'Valinnat tallennettu',
		'options' => 'valinnat',
		'page_already_used' => 'Tämä on jo sivun käytössä',
		'page_content_html' => 'Näytettävä sisältö - HTML sallittu:',
		'page_default_slug' => 'sivu-^',
		'page_heading' => 'Sivun yläreunassa näytettävä otsikko:',
		'page_name' => 'Sivun nimi (käytetään myös välilehtenä tai linkkinä):',
		'page_slug' => 'Sviun tunniste (URL:n osa):',
		'pages_explanation' => 'Valitse \'lisää sivu\' lisätäksesi mukautettua sisältöä Q2A sivustollesi, tai \'lisää linkki\' lisätäksesi linkin toiselle sivustolle.',
		'pages_title' => 'Sivut',
		'pause_mailing_button' => 'Pysäyty (pause) postitus',
		'per_ip_hour' => 'IP:tä/tunnissa',
		'per_user_hour' => 'käyttäjää/tunnissa',
		'permissions_title' => 'Oikeudet',
		'permit_to_view' => 'Näytetään käyttäjille:',
		'php_version' => 'PHP versio:',
		'pixels' => 'pikseliä',
		'plugin_module' => ' (liitännäinen: ^)',
		'plugin_pages_explanation' => 'Sivut näytetään liitännäisten kautta:',
		'plugins_title' => 'Liitännäiset',
		'points_defaults_shown' => 'Oletusarvot näkyvillä alla, mutta ei vielä voimassa:',
		'points_required' => 'Vaadittu pistemäärä saadakseen:',
		'points_title' => 'Pistettä',
		'points' => 'pistettä',
		'position' => 'Sijainti:',
		'posting_title' => 'Postitus',
		'profile_fields' => 'Käyttäjäprofiilin lisäkentät:',
		'q2a_build_date' => 'Q2A koostettu:',
		'q2a_db_size' => 'Tietokannan koko:',
		'q2a_db_version' => 'Q2A tietokannan versio:',
		'q2a_latest_version' => 'Viimeisin versio:',
		'q2a_version' => 'Question2Answer versio:',
		'question_lists' => 'Kysymyslistat',
		'question_pages' => 'Kysymyssivut',
		'recalc_categories_backpaths' => 'Määritellään uudelleen URL polkuja ^1 / ^2 kategorialle...',
		'recalc_categories_complete' => 'Kaikkien kategorioiden URL:t uudelleenmääritelty onnistuneesti.',
		'recalc_categories_note' => ' - kirjoitusten kategorioille ja kategoriamäärille',
		'recalc_categories_recounting' => 'Uudelleenlasketaan kysymyksiä ^1 / ^2 kategorialle...',
		'recalc_categories_updated' => 'Laskettiin uudelleen ^1 / ^2 kirjoitusta...',
		'recalc_categories' => 'Laske kategoriat uudelleen',
		'recalc_points_complete' => 'Käyttäjien pisteet laskettiin uudelleen onnistuneesti.',
		'recalc_points_note' => ' - käyttäjien sijoituksen ja pisteiden näyttämiseen',
		'recalc_points_recalced' => 'Pisteet laskettu uudelleen ^1 / ^2 käyttäjälle...',
		'recalc_points_usercount' => 'Arvioidaan käyttäjien kokonaismäärä...',
		'recalc_points' => 'Laske käyttäjien pisteet uudelleen',
		'recalc_posts_count' => 'Haetaan kysymysten, vastausten ja kommenttien kokonaismäärä...',
		'recalc_stop' => 'Lopeta uudelleen laskeminen',
		'recent_approve_title' => 'Tuoreet sisällöt, jotka odottavat hyväksyntää',
		'recent_hidden_title' => 'Tuoreet piilotetut sisällöt',
		'recount_posts_as_recounted' => 'Laskettiin vastausten määrä ja polttavuus ^1 / ^2 kirjoitukselle...',
		'recount_posts_complete' => 'Kaikki kirjoitukset laskettu uudelleen onnistuneesti.',
		'recount_posts_note' => ' - jokaisen kirjoituksen vastausten, peukkujen, liputuksien määrä ja polttavuus',
		'recount_posts_stop' => 'Lopeta uudelleen laskeminen',
		'recount_posts_votes_recounted' => 'Laskettiin uudelleen peukut ja liputukset ^1 / ^2 kirjoitukselle...',
		'recount_posts' => 'Laske uudelleen kirjoitukset',
		'refill_events_complete' => 'Tapahtumavirrat täytettiin uudelleen onnistuneesti',
		'refill_events_note' => ' - jokaisen käyttäjän päivityslistalle',
		'refill_events_refilled' => 'Täytetty uudelleen ^1 / ^2 kysymykselle...',
		'refill_events' => 'Täytä uudelleen tapahtumien virta',
		'reindex_content' => 'Indeksoi sisältö uudelleen',
		'reindex_content_note' => ' - etsi-toimintoa ja liittyvien kysymysten ehdotuksia varten',
		'reindex_content_stop' => 'Lopeta indeksointi',
		'reindex_pages_reindexed' => 'Indeksoitiin uudelleen ^1 / ^2 sivua...',
		'reindex_posts_complete' => 'Kaikki kirjoitukset indeksoitiin uudelleen onnistuneesti.',
		'reindex_posts_reindexed' => 'Indeksoitiin uudelleen ^1 / ^2 kirjoitusta...',
		'reindex_posts_wordcounted' => 'Laskettiin uudelleen ^1 / ^2 sanaa...',
		'requires_php_version' => 'Poissa käytöstä - vaatii PHP version ^ tai uudemman',
		'requires_q2a_version' => 'Poissa käytöstä - vaatii Question2Answer version ^ tai uudemman',
		'reset_options_button' => 'Palauta oletusarvot',
		'resume_mailing_button' => 'Jatka postitusta',
		'save_options_button' => 'Tallenna valinnat',
		'save_recalc_button' => 'Tallenna ja laske uudelleen',
		'send_test_button' => 'Lähetä testi minulle',
		'show_defaults_button' => 'Näytä oletusarvot',
		'slug_bad_chars' => 'Tunniste (slug) ei saa sisältää: ^',
		'slug_reserved' => 'Tämä tunniste (slug) on varattu toisen sivun käyttöön',
		'spam_title' => 'Roskaposti',
		'start_mailing_button' => 'Aloita postitus',
		'stats_title' => 'Tilastot',
		'stop_recalc_warning' => 'Tietokannan siivous on käynnissä. Jos suljet sivun nyt, toiminto keskeytyy.',
		'tag_pages' => 'Tunnistesivut',
		'tags_and_categories' => 'Tunnisteet ja kategoriat',
		'tags_not_shown' => 'Joitakin tunnisteita (tag) ei näytetä kysymyksissä.',
		'tags' => 'Tunnisteet',
		'test_sent_to_x' => 'Testiviesti lähetettiin osoitteeseen ^',
		'title_already_used' => 'Tämä arvo on jo toisen otsikon käytössä',
		'top_level_categories' => 'Päätason kategoriat:',
		'total_as' => 'Vastauksia yhteensä:',
		'total_cs' => 'Kommentteja yhteensä:',
		'total_qs' => 'Kysymyksiä yhteensä:',
		'unnamed_plugin' => 'Nimeämätön liitäänäinen',
		'upgrade_db' => 'Käyttämäsi Question2Answer tietokanta pitää ^1päivittää^2 tätä versiota varten.',
		'url_format_note' => 'Valinnat, joissa on ^ merkintä toimivat sivuston konfiguraatiossa. Hakukoneoptimointia varten (SEO), käytä ensimmäistä mahdollista ^ valintaa.',
		'user_pages' => 'Käyttäjien sivut',
		'user_title' => 'Käyttäjäsivun otsikko - HTML sallittu:',
		'user_titles' => 'Käyttäjien otsikot pisteiden perusteella:',
		'users_active' => 'Aktiiviset käyttäjät:',
		'users_must_have' => 'Käyttäjillä pitää olla',
		'users_posted' => 'Käyttäjät, jotka kirjoittivat:',
		'users_registered' => 'Rekisteröityneet käyttäjät:',
		'users_title' => 'Käyttäjät',
		'users_voted' => 'Käyttäjät, jotka peukuttivat:',
		'version_get_x' => 'hae ^',
		'version_requires_php' => '^1 vaatii PHP version ^2', 
		'version_requires_q2a' => '^1 vaatii Q2A version ^2', 
		'version_latest_unknown' => 'viimeisimmät tuntemattomat',
		'version_latest' => 'viimeisimmät',
		'viewing_title' => 'Katselu',
		'widget_all_pages' => 'Näytä vimpain tällä paikalla kaikilla sivuilla',
		'widget_global_options' => ' - ^1valinnat^2',
		'widget_name' => 'Vimpaimen nimi:',
		'widget_no_positions' => 'Vimpain on jo lisätty kaikkiin mahdollisiis paikkoihin.',
		'widget_not_available' => 'Vimpain ei ole saatavilla. Vimpaimen tarjoava liitännäinen on ehkä poistettu.',
		'widget_pages_explanation' => 'Näytä vimpain tässä paikassa seuraavilla sivuilla:',
		'widgets_explanation' => 'Tarjolla olevat vimpaimet:',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
