<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-admin.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases for admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php

        Finnish translation: kyyberi (jarkko.moilanen@ossoil.com)

*/

	return array(
		'active_widgets_explanation' => 'Aktiiviset vimpaimet:',
		'add_category_button' => 'Lisää kategoria',
		'add_field_button' => 'Lisää kenttä',
		'add_link_button' => 'Lisää linkki',
		'add_link_link' => ' - ^1lisää linkki^2',
		'add_new_field' => 'Lisää uusi kenttä',
		'add_new_title' => 'Lisää uusi otsikko',
		'add_page_button' => 'Lisää sivu',
		'add_title_button' => 'Lisää otsikko',
		'add_widget_button' => 'Lisää vimpain',
		'add_widget_link' => ' - ^1Lisää vimpain^2',
		'admin_title' => 'Hallinnointikeskus',
		'after_footer' => 'Linkkien jälkeen alaviitteessä',
		'after_main_menu' => 'Välilehtien jälkeen ylhäällä',
		'after_x_tab' => '"^" välilehden jälkeen',
		'after_x' => '"^" jälkeen',
		'moderate_title' => 'Moderoi',
		'basic_editor' => 'Peruseditori',
		'before_main_menu' => 'Ennen yläosan välilehtiä',
		'block_ips_note' => 'Käytä väliviivaa alueen määrittämiseen tai *:ä villinä korttina. Esimerkit: 192.168.0.4 , 192.168.0.0-192.168.0.31 , 192.168.0.*',
		'block_words_note' => 'Käytä *:ä villinä korttina. Esimerkit: puh (sisältää vain tasan sanat, joissa kirjaimet puh) , puh* (sisältää sanat, jotka alkavat puh) , puh*t (sisältää esimerkiksi sanat: puheet, puhtaat).',
		'cancel_mailing_button' => 'Peru sähköpostin lähettäminen',
		'categories_introduction' => 'Päästäksesi alkuun kategorioiden kanssa, valitse \'Lisää kategoria\'.',
		'categories_not_shown' => 'Joissakin kysymyksissä on kategoria ja niitä ei näytetä/listata.',
		'categories_title' => 'Kategoriat',
		'categories' => 'Kategoriat',
		'category_add_sub' => 'lisää alakategoria',
		'category_added' => 'Kategoria lisätty',
		'category_already_used' => 'Tämä kategoria on jo käytössä',
		'category_default_slug' => 'kategoria-^',
		'category_description' => 'Valinnainen kategorian kuvaus:',
		'category_max_depth_x' => 'Jotkin asetukset saattavat olla piilotettuja, jotta voidaan estää kategorian syvyys ^ tasolle.',
		'category_move_parent' => 'siirrä toisen kategorian alle',
		'category_name_first' => 'Ensimmäisen kategorian nimi:',
		'category_name' => 'Kategorian nimi:',
		'category_no_add_subs_x' => 'Tällä kategorialla ei voi olla alakategorioita, koska se on jo tasolla ^.',
		'category_no_delete_subs' => 'Kategoriaa ei voi poistaa, koska sillä on alakategorioita.',
		'category_no_sub_error' => '^q kysymyksillä tässä kategoriassa ei ole alakategorioita - ^1aseta alakategoria^2',
		'category_no_sub_to' => 'Siirrä kysymykset ilman alakategoriaa sijainnissa ^ uuteen paikkaan:',
		'category_no_subs' => 'Ei yhtään',
		'category_none_error' => '^q kysymyksillä ei ole kategoriaa - ^1aseta kategoria^2',
		'category_none_to' => 'Aseta kategoria kysymyksille, jotka ovat ilman kategoriaa:',
		'category_parent' => 'Ylempi kategoria:',
		'category_saved' => 'Kategoria tallennettu',
		'category_slug' => 'Kategoria tunniste - URL:n osa:',
		'category_subs' => 'Alakategoriat:',
		'category_top_level' => 'Ei ylempää tasoa (ylin taso)',
		'characters' => 'merkkiä',
		'check_language_suffix' => ' - ^1tarkista vaihtoehtoiset kielet^2',
		'click_name_edit' => 'Mukautetut sivut tai linkit:',
		'database_cleanup' => 'Tietokannan siivoustoiminnot',
		'delete_category_reassign' => 'Poista kategoria ja liitä kysymykset kategoriaan:',
		'delete_category' => 'Poista tämä kategoria',
		'delete_field' => 'Poista tämä kenttä',
		'delete_hidden_complete' => 'Kaikki piilotetut kysymykset ilman riippuvuuksia/viittauksia on poistettu',
		'delete_hidden_note' => ' - kaikki piilotetut kysymykset, vastaukset ja kommentit ilman riippuvuuksia/viittauksia',
		'delete_hidden' => 'Poista piilotetut kirjoitukset',
		'delete_link' => 'Poista tämä linkki',
		'delete_page' => 'Poista sivu',
		'delete_stop' => 'Lopeta poistaminen',
		'delete_title' => 'Poista otsikko',
		'delete_widget_position' => 'Poista vimpain tästä sijainnista',
		'edit_custom_page' => 'Muokkaa mukautettua sivua',
		'edit_field' => ' - ^1muokkaa kenttää^2',
		'edit_link' => ' - ^1muokkaa linkkiä^2',
		'edit_page' => ' - ^1muokkaa sivua^2',
		'edit_title' => ' - ^1muokkaa otsikkoa^2',
		'emails_per_minute' => 'sähköpostia minuutissa',
		'emails_title' => 'Sähköpostit',
		'feed_link_example' => 'Esimerkki syöte',
		'feed_link' => 'Syöte',
		'feeds_title' => 'RSS syötteet',
		'field_link_url' => 'Linkitetty URL',
		'field_multi_line' => 'Usean rivin sisältö',
		'field_name' => 'Kentän nimi:',
		'field_single_line' => 'Yhden rivin sisältö',
		'field_type' => 'Sisältötyyppi:',
		'first' => 'Ensimmäinen',
		'flagged_title' => 'Liputettu',
		'form_security_expired' => 'Lomakkeen turvakoodi on vanhentunut - yritä uudelleen',
		'from_anon' => 'Tuntemattomalta:',
		'from_users' => 'Käyttäjiltä:',
		'general_title' => 'Yleinen',
		'hidden_answers_deleted' => 'Poistettu ^1 / ^2 piilotettua vastausta...',
		'hidden_comments_deleted' => 'Poistettu ^1 / ^2 piilotettua kommenttia...',
		'hidden_questions_deleted' => 'Poistettu ^1 / ^2 piilotettua kysymystä...',
		'hotness_factors' => 'Kysymyksen polttavuuden suhteellinen tärkeys:',
		'hidden_title' => 'Piilotettu',
		'installed_plugins' => 'Asennetut liitännäiset:',
		'ip_address_pages' => 'IP osoitteiden sivu',
		'layout_title' => 'Asettelu',
		'link_name' => 'Linkin teksti:',
		'link_new_window' => 'Avaa linkki uuteen ikkunaan',
		'link_url' => 'Linkin URL-osoite - absoluuttinen tai relatiivinen suhteessa Q2A juureen:',
		'lists_title' => 'Listat',
		'mailing_complete' => 'Postitus on valmis',
		'mailing_explanation' => 'Käyttäjät voivat peruuttaa tilauksen profiilisivun kautta.',
		'mailing_progress' => 'Postitus ^1 / ^2 valmis...',
		'mailing_title' => 'Postitus',
		'mailing_unsubscribe' => 'An unsubscribe link will be added at the bottom of every message.',
		'maintenance_admin_only' => 'Your site is in ^1maintenance^2 and is currently inaccessible to regular users.',
		'maximum_x' => ' (max ^)',
		'module_x_database_init' => 'The ^1 ^2 module requires some ^3database initialization^4.',
		'most_flagged_title' => 'Flagged content',
		'mysql_version' => 'MySQL version:',
		'nav_links_explanation' => 'Show navigation links:',
		'nav_qa_is_home' => 'Q&A (links to home page)',
		'neat_urls_note' => ' (requires ^1htaccess^2 file)',
		'no_approve_found' => 'No content is waiting for approval',
		'no_classification' => 'None',
		'no_flagged_found' => 'No flagged content found',
		'no_hidden_found' => 'No hidden content found',
		'no_image_gd' => 'The installed version of PHP was compiled without GD image support, so users cannot upload their avatars directly.',
		'no_link' => 'No link',
		'no_multibyte' => 'The installed version of PHP was compiled without multibyte string support. Searching will be less effective for non-Roman characters.',
		'no_plugin_options' => 'None of your installed plugins have options to display.',
		'no_privileges' => 'Only administrators may access this page.',
		'not_logged_in' => 'Please ^1log in^2 as the administrator to access this page.',
		'opposite_main_menu' => 'Far end of tabs at top',
		'options_reset' => 'Options reset',
		'options_saved' => 'Options saved',
		'options' => 'options',
		'page_already_used' => 'This is already being used by a page',
		'page_content_html' => 'Content to display in page - HTML allowed:',
		'page_default_slug' => 'page-^',
		'page_heading' => 'Heading to display at top of page:',
		'page_name' => 'Name of page (also used for tab or link):',
		'page_slug' => 'Page slug (URL fragment):',
		'pages_explanation' => 'Click the \'Add Page\' button to add custom content to your Q2A site, or \'Add Link\' to link to any other web page.',
		'pages_title' => 'Pages',
		'pause_mailing_button' => 'Pause Mailing',
		'per_ip_hour' => 'per IP/hour',
		'per_user_hour' => 'per user/hour',
		'permissions_title' => 'Permissions',
		'permit_to_view' => 'Visible for:',
		'php_version' => 'PHP version:',
		'pixels' => 'pixels',
		'plugin_module' => ' (plugin module: ^)',
		'plugin_pages_explanation' => 'Pages available via plugins:',
		'plugins_title' => 'Plugins',
		'points_defaults_shown' => 'Defaults shown below but NOT YET APPLIED:',
		'points_required' => 'Points required to receive title:',
		'points_title' => 'Points',
		'points' => 'points',
		'position' => 'Position:',
		'posting_title' => 'Posting',
		'profile_fields' => 'Extra fields on user profile:',
		'q2a_build_date' => 'Build date:',
		'q2a_db_size' => 'Database size:',
		'q2a_db_version' => 'Q2A database version:',
		'q2a_latest_version' => 'Latest version:',
		'q2a_version' => 'Question2Answer version:',
		'question_lists' => 'Question lists',
		'question_pages' => 'Question pages',
		'recalc_categories_backpaths' => 'Recalculating URL paths for ^1 of ^2 categories...',
		'recalc_categories_complete' => 'All categories were successfully recalculated.',
		'recalc_categories_note' => ' - for post categories and category counts',
		'recalc_categories_recounting' => 'Recounting questions for ^1 of ^2 categories...',
		'recalc_categories_updated' => 'Recalculated for ^1 of ^2 posts...',
		'recalc_categories' => 'Recalculate categories',
		'recalc_points_complete' => 'All user points were successfully recalculated.',
		'recalc_points_note' => ' - for user ranking and points displays',
		'recalc_points_recalced' => 'Recalculated for ^1 of ^2 users...',
		'recalc_points_usercount' => 'Estimating total number of users...',
		'recalc_points' => 'Recalculate user points',
		'recalc_posts_count' => 'Getting total number of questions, answers and comments...',
		'recalc_stop' => 'Stop recalculating',
		'recent_approve_title' => 'Recent content waiting for approval',
		'recent_hidden_title' => 'Recent hidden content',
		'recount_posts_as_recounted' => 'Recounted answers and hotness for ^1 of ^2 posts...',
		'recount_posts_complete' => 'All posts were successfully recounted.',
		'recount_posts_note' => ' - the number of answers, votes, flags and hotness for each post',
		'recount_posts_stop' => 'Stop recounting',
		'recount_posts_votes_recounted' => 'Recounted votes and flags for ^1 of ^2 posts...',
		'recount_posts' => 'Recount posts',
		'refill_events_complete' => 'All events streams were successfully refilled',
		'refill_events_note' => ' - for each user\'s list of updates',
		'refill_events_refilled' => 'Refilled for ^1 of ^2 questions...',
		'refill_events' => 'Refill event streams',
		'reindex_content' => 'Reindex content',
		'reindex_content_note' => ' - for searching and related question suggestions',
		'reindex_content_stop' => 'Stop reindexing',
		'reindex_pages_reindexed' => 'Reindexed ^1 of ^2 pages...',
		'reindex_posts_complete' => 'All posts were successfully reindexed.',
		'reindex_posts_reindexed' => 'Reindexed ^1 of ^2 posts...',
		'reindex_posts_wordcounted' => 'Recounted ^1 of ^2 words...',
		'requires_php_version' => 'Disabled - requires PHP ^ or later',
		'requires_q2a_version' => 'Disabled - requires Question2Answer ^ or later',
		'reset_options_button' => 'Reset to Defaults',
		'resume_mailing_button' => 'Resume Mailing',
		'save_options_button' => 'Save Options',
		'save_recalc_button' => 'Save and Recalculate',
		'send_test_button' => 'Send Test to Me',
		'show_defaults_button' => 'Show Defaults',
		'slug_bad_chars' => 'The slug may not contain these characters: ^',
		'slug_reserved' => 'This slug is reserved for use by another page',
		'spam_title' => 'Spam',
		'start_mailing_button' => 'Start Mailing',
		'stats_title' => 'Stats',
		'stop_recalc_warning' => 'A database clean-up operation is running. If you close this page now, the operation will be interrupted.',
		'tag_pages' => 'Tag pages',
		'tags_and_categories' => 'Tags and Categories',
		'tags_not_shown' => 'Some questions have tags which will not be displayed.',
		'tags' => 'Tags',
		'test_sent_to_x' => 'The test message was sent to ^',
		'title_already_used' => 'This value is already being used by another title',
		'top_level_categories' => 'Top level categories:',
		'total_as' => 'Total answers:',
		'total_cs' => 'Total comments:',
		'total_qs' => 'Total questions:',
		'unnamed_plugin' => 'Unnamed Plugin',
		'upgrade_db' => 'Your Question2Answer database needs to be ^1upgraded^2 for this version.',
		'url_format_note' => 'Options with the ^ label are working for your site\'s configuration. For best search engine optimization (SEO), use the first ^ option available.',
		'user_pages' => 'User pages',
		'user_title' => 'User title - HTML allowed:',
		'user_titles' => 'User titles based on points:',
		'users_active' => 'Active users:',
		'users_must_have' => 'Users must have',
		'users_posted' => 'Users who posted:',
		'users_registered' => 'Registered users:',
		'users_title' => 'Users',
		'users_voted' => 'Users who voted:',
		'version_get_x' => 'get ^',
		'version_requires_php' => '^1 requires PHP ^2', 
		'version_requires_q2a' => '^1 requires Q2A ^2', 
		'version_latest_unknown' => 'latest unknown',
		'version_latest' => 'latest',
		'viewing_title' => 'Viewing',
		'widget_all_pages' => 'Show widget in this position on all available pages',
		'widget_global_options' => ' - ^1options^2',
		'widget_name' => 'Name of widget:',
		'widget_no_positions' => 'This widget has already been added to every available position.',
		'widget_not_available' => 'This widget is not available. This could be because the plugin providing the widget is no longer installed.',
		'widget_pages_explanation' => 'Show widget in this position on the following pages:',
		'widgets_explanation' => 'Available widgets:',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
