<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-main.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases commonly used throughout Q2A

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php

        Finnish translation: kyyberi (jarkko.moilanen@ossoil.com)

*/

	return array(
		'1_answer' => '1 vastaus',
		'1_comment' => '1 kommentti',
		'1_day' => '1 päivä',
		'1_disliked' => '1 inhous',
		'1_flag' => '1 liputus',
		'1_hour' => '1 tuntia',
		'1_liked' => '1 tykkäys',
		'1_minute' => '1 minuutti',
		'1_month' => '1 kuukausi',
		'1_point' => '1 piste',
		'1_question' => '1 kysymys',
		'1_second' => '1 sekunti',
		'1_tag' => '1 tagi',
		'1_user' => '1 käyttäjä',
		'1_view' => '1 näyttö',
		'1_vote' => '1 ääni',
		'1_week' => '1 viikko',
		'1_year' => '1 vuosi',
		'add_category_x_favorites' => 'Lisää kategoria ^ suosikkeihini',
		'add_favorites' => 'Lisää suosikkeihini',
		'add_tag_x_favorites' => 'Lisää tagi ^ suosikkeihini',
		'all_categories' => 'Kaikki kategoriat',
		'anonymous' => 'tuntematon',
		'answer_edited' => 'vastausta muokattu',
		'answer_reshown' => 'vastaus näytetty uudelleen',
		'answer_selected' => 'vastaus valittu',
		'answered_qs_in_x' => 'Eniten vastatut kysymykset näkymässä ^',
		'answered_qs_title' => 'Eniten vastatut kysymykset',
		'answered' => 'vastattu',
		'asked_related_q' => 'kysyi liittyvän kysymyksen',
		'asked' => 'kysytty',
		'by_x' => '^ toimesta',
		'cancel_button' => 'Peru',
		'closed' => 'suljettu',
		'comment_edited' => 'kommenttia muokattu',
		'comment_moved' => 'kommentti siirretty',
		'comment_reshown' => 'kommentti näytetty uudelleen',
		'commented' => 'kommentoitu',
		'date_day_min_digits' => 1, // 1 tai 2
		'date_format_other_years' => '^day. ^monthkuuta, ^year',
		'date_format_this_year' => '^day. ^monthkuuta',
		'date_month_1' => 'tammi',
		'date_month_2' => 'helmi',
		'date_month_3' => 'maalis',
		'date_month_4' => 'huhti',
		'date_month_5' => 'touko',
		'date_month_6' => 'kesä',
		'date_month_7' => 'heinä',
		'date_month_8' => 'elo',
		'date_month_9' => 'syys',
		'date_month_10' => 'loka',
		'date_month_11' => 'marras',
		'date_month_12' => 'joulu',
		'date_year_digits' => 4, // 2 or 4
		'edited' => 'muokattu',
		'field_required' => 'Älä jätä tätä kenttää tyhjäksi',
		'general_error' => 'Tapahtui palvelinvirhe - yritä uudelleen.',
		'hidden' => 'piilotettu',
		'highest_users' => 'Pistehirmut',
		'hot_qs_in_x' => '^ polttavat kysymykset',
		'hot_qs_title' => 'Polttavat kysymykset',
		'image_not_read' => 'Kuvaa ei voitu lukea. Sen sijaan käytä jotain seuraavista: ^',
		'image_too_big_x_pc' => 'Kuva on liian suuri (pikseleiltään). Skaalaa kuva kokoon ^% ja yritä uudelleenn.',
		'in_category_x' => 'kategoriassa ^',
		'ip_address_x' => 'IP osoite ^',
		'logged_in_x' => 'Terve ^',
		'max_length_x' => 'Enimmäispituus on ^ merkkiä',
		'me' => 'minä',
		'meta_order' => '^what^when^where^who', // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>
		'min_length_x' => 'Anna lisää tietoa - vähintään ^ merkkiä',
		'max_upload_size_x' => 'Enimmäiskoko on ^',
		'moved' => 'siirretty',
		'nav_account' => 'Käyttäjätilini',
		'nav_activity' => 'Kaikki toiminta',
		'nav_admin' => 'Ylläpito',
		'nav_ask' => 'Esitä kysymys',
		'nav_categories' => 'Kategoriat',
		'nav_feedback' => 'Lähetä palautetta',
		'nav_home' => 'Koti',
		'nav_hot' => 'Polttavat!',
		'nav_login' => 'Kirjaudu',
		'nav_logout' => 'Kirjaudu ulos',
		'nav_most_answers' => 'Eniten vastauksia',
		'nav_most_recent' => 'Viimeisimmät',
		'nav_most_views' => 'Eniten katseluita',
		'nav_most_votes' => 'Eniten peukkuja',
		'nav_no_answer' => 'Ei vastausta',
		'nav_no_selected_answer' => 'Ei valittua vastausta',
		'nav_no_upvoted_answer' => 'Ei peukutettua vastausta',
		'nav_qa' => 'Q&A',
		'nav_qs' => 'Kysymykset',
		'nav_register' => 'Rekisteröidy',
		'nav_tags' => 'Tagit',
		'nav_unanswered' => 'Ei vastausta',
		'nav_updates' => 'Päivitykseni',
		'nav_users' => 'Käyttäjät',
		'no_active_users' => 'Ei aktiivisia käyttäjiä',
		'no_answers_found' => 'Ei löytynyt vastauksia',
		'no_answers_in_x' => '^:ssa ei löytynyt vastauksia',
		'no_categories_found' => 'Ei löytynyt kategorioita',
		'no_category' => 'Ei kategoriaa',
		'no_comments_found' => 'Ei löytynyt kommentteja',
		'no_comments_in_x' => '^:ssa ei löytynyt kommentteja',
		'no_questions_found' => 'Ei löytynyt kysymyksiä',
		'no_questions_in_x' => '^:ssa ei löytynyt kysymyksiä',
		'no_related_qs_title' => 'Ei löytynyt asiaan liittyviä kysymyksiä',
		'no_results_for_x' => 'Ei löytynyt tuloksia haulle: ^',
		'no_tags_found' => 'Ei löytynyt tageja',
		'no_una_questions_found' => 'Ei löytynyt vastaamattomia kysymyksiä',
		'no_una_questions_in_x' => '^:sta ei löytynyt vastaamattomia kysymyksiä',
		'no_unselected_qs_found' => 'Ei löytynyt kysymyksiä ilman valittua vastausta',
		'no_unupvoteda_qs_found' => 'Ei löytynyt kysymyksiä ilamn ylöspäin äänestettyä vastausta',
		'page_label' => 'Sivu:',
		'page_next' => 'Seuraava',
		'page_not_found' => 'Sivua ei löytynyt',
		'page_prev' => 'Edellinen',
		'popular_tags' => 'Suosituimmat tagit',
		'questions_tagged_x' => 'Viimeisimmät tagatut kysymykset ^',
		'recategorized' => 'uudelleen kategorisoitu',
		'recent_activity_in_x' => 'Viimeisimmät aktiviteetit ^:ssa',
		'recent_activity_title' => 'Viimeisimmät aktiviteetit',
		'recent_as_in_x' => 'Viimeksi vastatut kysymykset ^:ssa',
		'recent_as_title' => 'Viimeksi vastatut kysymykset',
		'recent_cs_in_x' => 'Viimeksi lisätyt kommentit ^:ssa',
		'recent_cs_title' => 'Viimeksi lisätyt kommentit',
		'recent_qs_as_in_x' => 'Viimeisimmät kysymykset ja vastaukset ^:ssa',
		'recent_qs_as_title' => 'Viimeisimmät kysymykset ja vastaukset',
		'recent_qs_in_x' => 'Tuoreimmat kysymykset ^:ssa',
		'recent_qs_title' => 'Tuoreimmat kysymykset',
		'related_qs_title' => 'Liittyvät kysymykset',
		'remove_favorites' => 'Poista suosikeistani',
		'remove_x_favorites' => 'Poista ^ suosikeistani',
		'reopened' => 'avattu uudelleen',
		'reshown' => 'näytetty uudelleen',
		'results_for_x' => 'Tulokset haulle ^',
		'retagged' => 'uudelleen tagattu',
		'save_button' => 'Tallenna muutokset',
		'search_button' => 'Etsi',
		'search_explanation' => 'Kirjoita hakusi kenttään ja yritä uudelleen.',
		'search_title' => 'Hakutulokset',
		'selected' => 'valitut',
		'send_button' => 'Lähetä',
		'suggest_ask' => 'Auta ^1esittämällä kysymys^2.',
		'suggest_category_qs' => 'Nähdäksesi lisää, valitse ^1kysymykset tässä kategoriassa^2.',
		'suggest_qs_tags' => 'Nähdäksesi lisää, valitse ^1kaikki kysymykset^2 tai ^3suositut tagit^4.',
		'suggest_qs' => 'Nähdäksesi lisää, valitse ^1kaikki kysymykset^2.',
		'unanswered_qs_in_x' => 'Kysymykset ilman vastausta ^:ssa',
		'unanswered_qs_title' => 'Tuoreet kysymykset ilman vastausta',
		'unselected_qs_in_x' => 'Kysymykset ilman valittua vastausta ^:ssa',
		'unselected_qs_title' => 'Tuoreet kysymykset ilman valittua vastausta',
		'unupvoteda_qs_in_x' => 'Kysymykset ilman ylöspeukutusta ^:ssa',
		'unupvoteda_qs_title' => 'Tuoreet kysymykset ilman ylöspeukutettua vastausta',
		'upload_limit' => 'Liian monta latausta - yritä tunnin kuluttua uudelleen',
		'view_q_must_confirm' => '^5Vahvista sähköpostiosoitteesi^6 nähdäksesi kysymyssivut.',
		'view_q_must_login' => '^1Kirjaudu sisään^2 tai ^3rekisteröidy^4 nähdäksesi kysymyssivut.',
		'viewed_qs_in_x' => 'Eniten katsotut kysymykset ^:ssa',
		'viewed_qs_title' => 'Eniten katsotut kysymykset',
		'vote_disabled_down' => 'Peukutus alas on sallittu vain joillekin käyttäjille',
		'vote_disabled_hidden_a' => 'Et voi peukuttaa piilotettuja vastauksia',
		'vote_disabled_hidden_q' => 'Et voi peukuttaa piilotettuja kysymyksiä',
		'vote_disabled_level' => 'Peukutus alas on sallittu vain joillekin käyttäjille',
		'vote_disabled_my_a' => 'Et voi peukuttaa omia vastauksiasi',
		'vote_disabled_my_q' => 'Et voi peukuttaa omia kysymyksiäsi',
		'vote_disabled_q_page_only' => 'Lue tämä kysymys peukuttaaksesi',
		'vote_down_must_confirm' => '^5Vahvista sähköpostiosoitteesi^6 peukuttaaksesi alas.',
		'vote_down_popup' => 'Klikkaa peukuttaaksesi alas',
		'vote_limit' => 'Liian monta peukutusta - yritä uudelleen tunnin kuluttua',
		'vote_must_confirm' => '^5Vahvista sähköpostiosoitteesi^6 peukuttaaksesi.',
		'vote_must_login' => '^1Kirjaudu sisään^2 tai ^3rekisteröidy^4 peukuttaaksesi.',
		'vote_not_allowed' => 'Tämän kohdalla peukutus ei ole sallittu',
		'vote_up_popup' => 'Klikkaa peukuttaaksesi ylös',
		'voted_down_popup' => 'Olet peukuttanut tämän alaspäin - klikkaamalla poistat peukutuksen',
		'voted_qs_in_x' => 'Eniten peukkuja saaneet kysymykset ^:ssa',
		'voted_qs_title' => 'Eniten kannatusta saaneet kysymykset',
		'voted_up_popup' => 'Olet antanut kannatusäänen - klikkaa tästä peruaksesi kannatuksesi',
		'x_ago' => '^ sitten',
		'x_answers' => '^ vastausta',
		'x_comments' => '^ kommenttia',
		'x_days' => '^ päivää',
		'x_disliked' => '^ ei tykkää',
		'x_flags' => '^ lippua',
		'x_hours' => '^ tuntia',
		'x_liked' => '^ tykkää',
		'x_minutes' => '^ minuuttia',
		'x_months' => '^ kuukautta',
		'x_points' => '^ pistettä',
		'x_questions' => '^ kysymystä',
		'x_seconds' => '^ sekuntia',
		'x_tags' => '^ tagia',
		'x_users' => '^ käyttäjää',
		'x_views' => '^ lukukertaa',
		'x_votes' => '^ ääntä',
		'x_weeks' => '^ viikkoa',
		'x_years' => '^ vuotta',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
