<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-question.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases for question page


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer_title' => '1 vastaus',
		'a_convert_to_c_on' => 'Muunna tämä vastaus kommentiksi kysymykseen:',
		'a_convert_to_c' => 'Muunna tämä vastaus kommentiksi',
		'a_convert_warn_cs' => 'Warning: This conversion cannot be reversed and will also move this answer\'s comments.',
		'a_convert_warn' => 'Warning: This conversion cannot be reversed.',
		'a_notify_email' => 'Email me at this address if my answer is selected or commented on:',
		'a_notify_label' => 'Email me if my answer is selected or commented on',
		'a_notify_x_label' => 'Email me (^) if my answer is selected or commented on',
		'a_waiting_your_approval' => 'This answer is waiting for your approval',
		'a_your_waiting_approval' => 'Your answer will be checked and approved shortly.',
		'add_answer_button' => 'Add answer',
		'add_comment_button' => 'Add comment',
		'add_q_favorites' => 'Add this question to my favorites',
		'anon_name_label' => 'Your name to display (optional):',
		'answer_button' => 'answer',
		'answer_limit' => 'Too many answers received - please try again in an hour',
		'answer_must_confirm' => 'Please ^5confirm your email address^6 to answer this question.',
		'answer_must_login' => 'Please ^1log in^2 or ^3register^4 to answer this question.',
		'answer_q_popup' => 'Answer this question',
		'approve_button' => 'approve',
		'ask_button' => 'Ask the Question',
		'ask_follow_from_a' => 'Your question will be related to this answer:',
		'ask_follow_title' => 'Ask a related question',
		'ask_limit' => 'Too many questions received - please try again in an hour',
		'ask_must_confirm' => 'Please ^5confirm your email address^6 to ask a question.',
		'ask_must_login' => 'Please ^1log in^2 or ^3register^4 to ask a question.',
		'ask_same_q' => 'Before proceeding, please check your question was not asked already:',
		'ask_title' => 'Ask a question',
		'c_notify_email' => 'Email me at this address if a comment is added after mine:',
		'c_notify_label' => 'Email me if a comment is added after mine',
		'c_notify_x_label' => 'Email me (^) if a comment is added after mine',
		'c_waiting_your_approval' => 'This comment is waiting for your approval',
		'c_your_waiting_approval' => 'Your comment will be checked and approved shortly.',
		'category_js_note' => 'To select any category, please enable Javascript in your web browser.',
		'category_required' => 'Please choose a category',
		'claim_button' => 'I wrote this',
		'clear_flags_button' => 'clear flags',
		'clear_flags_popup' => 'Remove flags by all users',
		'close_button' => 'close',
		'close_duplicate_error' => 'The duplicate question could not be found - please try entering the number from a different question URL, e.g. 123.',
		'close_duplicate' => 'This is a duplicate of another question',
		'close_form_button' => 'Close question',
		'close_form_title' => 'Close this question',
		'close_original_note' => 'You can also enter the question number from the URL, e.g. 123.',
		'close_original_title' => 'URL of the original question:',
		'close_q_popup' => 'Close this question to any new answers',
		'close_reason_title' => 'Reason for closing this question:',
		'closed_as_duplicate' => 'closed as a duplicate of:',
		'closed_with_note' => 'closed with the note:',
		'comment_a_popup' => 'Add a comment on this answer',
		'comment_button' => 'comment',
		'comment_limit' => 'Too many comments received - please try again in an hour',
		'comment_must_confirm' => 'Please ^5confirm your email address^6 to add a comment.',
		'comment_must_login' => 'Please ^1log in^2 or ^3register^4 to add a comment.',
		'comment_on_a' => 'On answer: ',
		'comment_on_q' => 'On question: ',
		'comment_q_popup' => 'Add a comment on this question',
		'delete_a_popup' => 'Delete this answer permanently',
		'delete_button' => 'delete',
		'delete_c_popup' => 'Delete this comment permanently',
		'delete_q_popup' => 'Delete this question permanently',
		'duplicate_content' => 'Your submission appears to be a duplicate.',
		'edit_a_popup' => 'Edit this answer',
		'edit_a_title' => 'Edit answer',
		'edit_button' => 'edit',
		'edit_c_popup' => 'Edit this comment',
		'edit_c_title' => 'Edit comment',
		'edit_must_confirm' => 'Please ^5confirm your email address^6 to edit this.',
		'edit_must_login' => 'Please ^1log in^2 or ^3register^4 to edit this.',
		'edit_q_popup' => 'Edit this question',
		'edit_q_title' => 'Edit Question',
		'example_tags' => 'Example tags: ',
		'flag_a_popup' => 'Flag this answer as spam or inappropriate',
		'flag_button' => 'flag',
		'flag_c_popup' => 'Flag this comment as spam or inappropriate',
		'flag_hide_button' => 'flag and hide',
		'flag_limit' => 'Too many posts flagged - please try again in an hour',
		'flag_must_confirm' => 'Please ^5confirm your email address^6 to flag posts.',
		'flag_must_login' => 'Please ^1log in^2 or ^3register^4 to flag posts.',
		'flag_not_allowed' => 'Flagging this is not allowed',
		'flag_q_popup' => 'Flag this question as spam or inappropriate',
		'follow_a_popup' => 'Ask a new question relating to this answer',
		'follow_button' => 'ask related question',
		'follows_a' => 'related to an answer for:',
		'follows_q' => 'about the question:',
		'hide_a_popup' => 'Hide this answer',
		'hide_button' => 'hide',
		'hide_c_popup' => 'Hide this comment',
		'hide_q_popup' => 'Hide this question',
		'matching_tags' => 'Matching tags: ',
		'max_tags_x' => 'A maximum of ^ tags are allowed',
		'min_tags_x' => 'Please provide at least ^ tag/s',
		'notify_email_note' => 'Privacy: Your email address will only be used for sending these notifications.',
		'q_category_label' => 'Category:',
		'q_content_label' => 'More information for the question:',
		'q_hidden_author' => 'This question has been hidden by its author',
		'q_hidden_flagged' => 'This question has been flagged and hidden',
		'q_hidden_other' => 'This question has been hidden',
		'q_notify_email' => 'Email me at this address if my question is answered or commented on:',
		'q_notify_label' => 'Email me if my question is answered or commented on',
		'q_notify_x_label' => 'Lähetä minulle sähköpostia (^) kun kysymykseeni tulee vastaus tai kommentti',
		'q_tags_comma_label' => 'Tagit - käytä pilkkua (,) erottimena:',
		'q_tags_label' => 'Tagit - käytä väliviivaa yhdistääksesi sanoja:',
		'q_title_label' => 'Kysymys yhdellä lauseella:',
		'q_waiting_approval' => 'Kysymys odottaa hyväksyntää',
		'q_waiting_your_approval' => 'Kysymys odottaa hyväksyntääsi',
		'q_your_waiting_approval' => 'Kysymyksesi arvioidaan ja hyväksytään pian.',
		'recat_button' => 'Muuta kategoria',
		'recat_popup' => 'Muuta tämän kysymyksen kategoriaa',
		'recat_q_title' => 'Muuta kysymyksen kategoriaa',
		'reject_button' => 'hylkää',
		'remove_q_favorites' => 'Poista tämä kysymys suosikeistani',
		'reopen_button' => 'avaa uudelleen',
		'reply_button' => 'vastaa',
		'reply_c_popup' => 'Vastaa kommenttiin',
		'reshow_button' => 'Näytä uudelleen',
		'retag_button' => 'Muuta tagit',
		'retag_cat_popup' => 'Muuta tämän kysymyksen kategoriaa tai tageja',
		'retag_popup' => 'Muuta tämän kysymyksen tageja',
		'retag_q_title' => 'Muuta kysymyksen tageja',
		'select_popup' => 'Paina tästä valitaksesi parhaaksi vastaukseksi',
		'select_text' => 'Paras vastaus',
		'show_1_comment' => 'Näytä 1 kommentti',
		'show_1_previous_comment' => 'Näytä edellinen kommentti',
		'show_x_comments' => 'Näytä ^ kommenttia',
		'show_x_previous_comments' => 'Näytä ^ edellistä kommenttia',
		'unflag_button' => 'poista lippu',
		'unflag_popup' => 'Poista lisäämäsi lippu',
		'unselect_popup' => 'Valitse poistaaksesi valinnan',
		'x_answers_title' => '^ Vastausta',
		'your_answer_title' => 'Vastauksesi',
		'your_comment_a' => 'Kommenttisi tähän vastaukseen:',
		'your_comment_q' => 'Kommenttisi tähän kysymykseen:',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
