<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-main.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer' => '1 vastaus',
		'1_comment' => '1 kommentti',
		'1_day' => '1 päivä',
		'1_disliked' => '1 inhous',
		'1_flag' => '1 liputus',
		'1_hour' => '1 tuntia',
		'1_liked' => '1 tykkäys',
		'1_minute' => '1 minuutti',
		'1_month' => '1 kuukausi',
		'1_point' => '1 piste',
		'1_question' => '1 kysymys',
		'1_second' => '1 sekunti',
		'1_tag' => '1 tagi',
		'1_user' => '1 käyttäjä',
		'1_view' => '1 näyttö',
		'1_vote' => '1 ääni',
		'1_week' => '1 viikko',
		'1_year' => '1 vuosi',
		'add_category_x_favorites' => 'Lisää kategoria ^ suosikkeihini',
		'add_favorites' => 'Lisää suosikkeihini',
		'add_tag_x_favorites' => 'Lisää tagi ^ suosikkeihini',
		'all_categories' => 'Kaikki kategoriat',
		'anonymous' => 'tuntematon',
		'answer_edited' => 'vastausta muokattu',
		'answer_reshown' => 'vastaus näytetty uudelleen',
		'answer_selected' => 'vastaus valittu',
		'answered_qs_in_x' => 'Eniten vastatut kysymykset näkymässä ^',
		'answered_qs_title' => 'Eniten vastatut kysymykset',
		'answered' => 'vastattu',
		'asked_related_q' => 'kysyi liittyvän kysymyksen',
		'asked' => 'kysytty',
		'by_x' => '^ toimesta',
		'cancel_button' => 'Peru',
		'closed' => 'suljettu',
		'comment_edited' => 'kommenttia muokattu',
		'comment_moved' => 'kommentti siirretty',
		'comment_reshown' => 'kommentti näytetty uudelleen',
		'commented' => 'kommentoitu',
		'date_day_min_digits' => 1, // 1 tai 2
		'date_format_other_years' => '^kuukausi ^päivä, ^vuosi',
		'date_format_this_year' => '^kuukausi ^päivä',
		'date_month_1' => 'Tammi',
		'date_month_2' => 'Helmi',
		'date_month_3' => 'Maalis',
		'date_month_4' => 'Huhti',
		'date_month_5' => 'Touko',
		'date_month_6' => 'Kesä',
		'date_month_7' => 'Heinä',
		'date_month_8' => 'Elo',
		'date_month_9' => 'Syys',
		'date_month_10' => 'Loka',
		'date_month_11' => 'Marras',
		'date_month_12' => 'Joulu',
		'date_year_digits' => 4, // 2 or 4
		'edited' => 'muokattu',
		'field_required' => 'Älä jätä tätä kenttää tyhjäksi',
		'general_error' => 'Tapahtui palvelinvirhe - yritä uudelleen.',
		'hidden' => 'piilotettu',
		'highest_users' => 'Pistehirmut',
		'hot_qs_in_x' => '^ polttavat kysymykset',
		'hot_qs_title' => 'Polttavat kysymykset',
		'image_not_read' => 'Kuvaa ei voitu lukea. Sen sijaan käytä jotain seuraavista: ^',
		'image_too_big_x_pc' => 'Kuva on liian suuri (pikseleiltään). Skaalaa kuva kokoon ^% ja yritä uudelleenn.',
		'in_category_x' => 'kategoriassa ^',
		'ip_address_x' => 'IP osoite ^',
		'logged_in_x' => 'Terve ^',
		'max_length_x' => 'Enimmäispituus on ^ merkkiä',
		'me' => 'minä',
		'meta_order' => '^what^when^where^who', // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>
		'min_length_x' => 'Anna lisää tietoa - vähintään ^ merkkiä',
		'max_upload_size_x' => 'Enimmäiskoko on ^',
		'moved' => 'siirretty',
		'nav_account' => 'Käyttäjätilini',
		'nav_activity' => 'Kaikki aktiivisuus',
		'nav_admin' => 'Ylläpitäjä',
		'nav_ask' => 'Esitä kysymys',
		'nav_categories' => 'Kategoriat',
		'nav_feedback' => 'Lähetä palautetta',
		'nav_home' => 'Koti',
		'nav_hot' => 'Polttavat!',
		'nav_login' => 'Kirjaudu',
		'nav_logout' => 'Kirjaudu ulos',
		'nav_most_answers' => 'Eniten vastauksia',
		'nav_most_recent' => 'Viimeisimmät',
		'nav_most_views' => 'Eniten katseluita',
		'nav_most_votes' => 'Eniten ääniä',
		'nav_no_answer' => 'Ei vastausta',
		'nav_no_selected_answer' => 'Ei valittua vastausta',
		'nav_no_upvoted_answer' => 'Ei äänestettyä vastausta',
		'nav_qa' => 'Q&A',
		'nav_qs' => 'Kysymykset',
		'nav_register' => 'Rekisteröidy',
		'nav_tags' => 'Tagit',
		'nav_unanswered' => 'Ei vastausta',
		'nav_updates' => 'Päivitykseni',
		'nav_users' => 'Käyttäjät',
		'no_active_users' => 'No active users found',
		'no_answers_found' => 'No answers found',
		'no_answers_in_x' => 'No answers in ^',
		'no_categories_found' => 'No categories found',
		'no_category' => 'No category',
		'no_comments_found' => 'No comments found',
		'no_comments_in_x' => 'No comments in ^',
		'no_questions_found' => 'No questions found',
		'no_questions_in_x' => 'No questions in ^',
		'no_related_qs_title' => 'No related questions found',
		'no_results_for_x' => 'No results found for ^',
		'no_tags_found' => 'No tags found',
		'no_una_questions_found' => 'No unanswered questions found',
		'no_una_questions_in_x' => 'No unanswered questions in ^',
		'no_unselected_qs_found' => 'No questions found without a selected answer',
		'no_unupvoteda_qs_found' => 'No questions found without an upvoted answer',
		'page_label' => 'Page:',
		'page_next' => 'next',
		'page_not_found' => 'Page not found',
		'page_prev' => 'prev',
		'popular_tags' => 'Most popular tags',
		'questions_tagged_x' => 'Recent questions tagged ^',
		'recategorized' => 'recategorized',
		'recent_activity_in_x' => 'Recent activity in ^',
		'recent_activity_title' => 'Recent activity',
		'recent_as_in_x' => 'Recently answered questions in ^',
		'recent_as_title' => 'Recently answered questions',
		'recent_cs_in_x' => 'Recently added comments in ^',
		'recent_cs_title' => 'Recently added comments',
		'recent_qs_as_in_x' => 'Recent questions and answers in ^',
		'recent_qs_as_title' => 'Recent questions and answers',
		'recent_qs_in_x' => 'Recent questions in ^',
		'recent_qs_title' => 'Recent questions',
		'related_qs_title' => 'Related questions',
		'remove_favorites' => 'Remove from my favorites',
		'remove_x_favorites' => 'Remove ^ from my favorites',
		'reopened' => 'reopened',
		'reshown' => 'reshown',
		'results_for_x' => 'Search results for ^',
		'retagged' => 'retagged',
		'save_button' => 'Save Changes',
		'search_button' => 'Search',
		'search_explanation' => 'Please enter some text into the search box and try again.',
		'search_title' => 'Search results',
		'selected' => 'selected',
		'send_button' => 'Send',
		'suggest_ask' => 'Help get things started by ^1asking a question^2.',
		'suggest_category_qs' => 'To see more, click for all the ^1questions in this category^2.',
		'suggest_qs_tags' => 'To see more, click for the ^1full list of questions^2 or ^3popular tags^4.',
		'suggest_qs' => 'To see more, click for the ^1full list of questions^2.',
		'unanswered_qs_in_x' => 'Questions without answers in ^',
		'unanswered_qs_title' => 'Recent questions without answers',
		'unselected_qs_in_x' => 'Questions without a selected answer in ^',
		'unselected_qs_title' => 'Recent questions without a selected answer',
		'unupvoteda_qs_in_x' => 'Questions without an upvoted answer in ^',
		'unupvoteda_qs_title' => 'Recent questions without an upvoted answer',
		'upload_limit' => 'Too many uploads - please try again in an hour',
		'view_q_must_confirm' => 'Please ^5confirm your email address^6 to view question pages.',
		'view_q_must_login' => 'Please ^1log in^2 or ^3register^4 to view question pages.',
		'viewed_qs_in_x' => 'Most viewed questions in ^',
		'viewed_qs_title' => 'Most viewed questions',
		'vote_disabled_down' => 'Voting down is only available to some users',
		'vote_disabled_hidden_a' => 'You cannot vote on hidden answers',
		'vote_disabled_hidden_q' => 'You cannot vote on hidden questions',
		'vote_disabled_level' => 'Voting is only available to some users',
		'vote_disabled_my_a' => 'You cannot vote on your own answers',
		'vote_disabled_my_q' => 'You cannot vote on your own questions',
		'vote_disabled_q_page_only' => 'Please view this question to vote',
		'vote_down_must_confirm' => 'Please ^5confirm your email address^6 to vote down.',
		'vote_down_popup' => 'Click to vote down',
		'vote_limit' => 'Too many votes received - please try again in an hour',
		'vote_must_confirm' => 'Please ^5confirm your email address^6 to vote.',
		'vote_must_login' => 'Please ^1log in^2 or ^3register^4 to vote.',
		'vote_not_allowed' => 'Voting on this is not allowed',
		'vote_up_popup' => 'Click to vote up',
		'voted_down_popup' => 'You have voted this down - click to remove vote',
		'voted_qs_in_x' => 'Highest voted questions in ^',
		'voted_qs_title' => 'Highest voted questions',
		'voted_up_popup' => 'You have voted this up - click to remove vote',
		'x_ago' => '^ ago',
		'x_answers' => '^ answers',
		'x_comments' => '^ comments',
		'x_days' => '^ days',
		'x_disliked' => '^ dislike',
		'x_flags' => '^ flags',
		'x_hours' => '^ hours',
		'x_liked' => '^ like',
		'x_minutes' => '^ minutes',
		'x_months' => '^ months',
		'x_points' => '^ points',
		'x_questions' => '^ questions',
		'x_seconds' => '^ seconds',
		'x_tags' => '^ tags',
		'x_users' => '^ users',
		'x_views' => '^ views',
		'x_votes' => '^ votes',
		'x_weeks' => '^ weeks',
		'x_years' => '^ years',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/
